services:
  postgresql-product:
    container_name: product_ms_pg_sql
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: firas
      POSTGRES_PASSWORD: Firas123@
      POSTGRES_DB: ecommerce_product_cataloge
      PGDATA: /data/postgres
    volumes:
      - postgres-product_db:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - ms-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U firas -d ecommerce_product_cataloge" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb-user:
    image: mongo:7.0.5
    container_name: mongo_db_user
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=firas
      - MONGO_INITDB_ROOT_PASSWORD=firas
      - MONGO_INITDB_DATABASE=user_db




networks:
  ms-net:
    driver: bridge

volumes:
  postgres-product_db:
  mongo: