spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 20000
  config:
    import: configserver:http://localhost:8888
  application:
    name: gateway-service