spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


